# generated by datamodel-codegen:
#   filename:  swagger-v3.json
#   timestamp: 2026-03-30T21:47:32+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel

from . import Record_string


class SubscriptionDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float
    field_id: str
    created_at: str
    updated_at: str
    started_at: str | None = None
    ended_at: str | None = None
    subscription: float


class PaginationInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    total: Annotated[int, Field(ge=0)]
    page: Annotated[int, Field(ge=1)]
    limit: Annotated[int | None, Field(ge=1)] = None
    totalPages: Annotated[int, Field(ge=1)]


class PaginatedResponseSubscriptionDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[SubscriptionDto]
    pagination: PaginationInfo


class UUIDModel(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='UUID string',
            pattern='^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
        ),
    ]


class SubscriptionsSortBy(Enum):
    created_at = 'created_at'
    updated_at = 'updated_at'


class Order(Enum):
    asc = 'asc'
    desc = 'desc'


class GetSubscriptionsQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: float | None = 1
    limit: float | None = None
    order: Order | None = 'asc'
    sort_by: Annotated[
        SubscriptionsSortBy | None, Field(description='Column to sort by')
    ] = None


class SingleResponseSubscriptionDtoArray(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[SubscriptionDto]
    message: str | None = None


class CreateSubscriptionBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_id: str
    subscription_id: float
    started_at: str | None = None
    ended_at: str | None = None


class ProjectDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[UUID, Field(description='Project ID')]
    name: str | None = 'New Project'
    abbreviation: str | None = 'NE'
    logo_path: str | None = None
    created_at: AwareDatetime | None = '2026-03-30T15:43:38.201Z'
    updated_at: AwareDatetime | None = '2026-03-30T15:43:38.201Z'


class PaginatedResponseProjectDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[ProjectDto]
    pagination: PaginationInfo


class Lang(Enum):
    en = 'en'
    nl = 'nl'
    de = 'de'
    fr = 'fr'


class SortBy(Enum):
    name = 'name'
    created_at = 'created_at'
    updated_at = 'updated_at'


class GetProjectsQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: float | None = 1
    limit: float | None = None
    order: Order | None = 'asc'
    lang: Lang | None = 'en'
    sort_by: SortBy | None = 'name'


class SingleResponseProjectDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: ProjectDto
    message: str | None = None


class UpdateProjectBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(description='Project name', examples=['My Project'])]
    abbreviation: Annotated[
        str | None,
        Field(description='Project abbreviation (optional)', examples=['MP']),
    ] = None


class CreateProjectBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(description='Project name', examples=['My Project'])]
    abbreviation: Annotated[
        str | None,
        Field(description='Project abbreviation (optional)', examples=['MP']),
    ] = None
    user_id: Annotated[
        str,
        Field(
            description='User ID of creator',
            examples=['bd4b4657-c165-482b-84ea-9781c6825305'],
        ),
    ]


class ProjectRole(Enum):
    member = 'member'
    owner = 'owner'


class UpdateUserRoleBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: ProjectRole


class UserDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    username: str | None = None
    name: str | None = None
    email: str
    phonenumber: str | None = None
    enabled: bool
    created_at: str
    updated_at: str


class ProjectUserDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: str
    joined_at: str
    user: UserDto


class PaginatedResponseProjectUserDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[ProjectUserDto]
    pagination: PaginationInfo


class ReportDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    title: str
    path: str
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    field_ids: list[str]
    observation_ids: list[str]


class PaginatedResponseReportDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[ReportDto]
    pagination: PaginationInfo


class RefType(Enum):
    field = 'field'
    observation = 'observation'


class ReportReferenceBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ref_id: UUID
    ref_type: RefType


class ServiceDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float
    name: str


class SendInviteBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: str
    role: ProjectRole


class Role(Enum):
    member = 'member'
    owner = 'owner'


class ValidateInviteResponseDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    project: ProjectDto
    email: str
    role: Role
    expires_at: AwareDatetime


class ProjectInviteDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: str
    role: str
    created_at: str
    expires_at: str


class ProjectInvitesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[ProjectInviteDto]


class UnitDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float
    unit: str
    description: str
    min_value: float
    max_value: float


class ObservationParametersDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float
    name: str
    unit: UnitDto
    created_at: AwareDatetime
    updated_at: AwareDatetime


class PaginatedResponseObservationParametersDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[ObservationParametersDto]
    pagination: PaginationInfo


class SupportedLanguage(Enum):
    en = 'en'
    nl = 'nl'
    de = 'de'
    fr = 'fr'


class ObservationValueDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float
    unit: str
    value: float
    operator: str
    type_name: str
    target_min: float
    target_max: float


class ObservationDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    observed_at: str
    reported_at: str
    updated_at: str
    reference_code: str
    geometry: str
    measurements: list[ObservationValueDto] | None = None


class PaginatedResponseObservationDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[ObservationDto]
    pagination: PaginationInfo


class Type(Enum):
    Feature = 'Feature'


class GeoJsonFeature(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    geometry: Any
    properties: Record_string.AnyModel


class Type1(Enum):
    FeatureCollection = 'FeatureCollection'


class GeoJsonFeatureCollection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type1
    features: list[GeoJsonFeature]


class ObsSortBy(Enum):
    name = 'name'
    created_at = 'created_at'
    updated_at = 'updated_at'


class ObsoutputFormat(Enum):
    wkt = 'wkt'
    geojson = 'geojson'


class GetObsQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: float | None = 1
    limit: float | None = None
    order: Order | None = 'asc'
    lang: Annotated[
        SupportedLanguage | None, Field(description='Language for field labels')
    ] = None
    sort_by: Annotated[ObsSortBy | None, Field(description='Column to sort by')] = None
    projectCollectionId: Annotated[
        str | None, Field(description='Optional project collection filter')
    ] = None
    crs: Annotated[
        float | None, Field(description='Target CRS (coordinate reference system)')
    ] = 4326
    output_format: ObsoutputFormat | None = None


class Type2(Enum):
    Point = 'Point'


class CreateObsGeometry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type2
    coordinates: list[float]


class ObsGeometryInput(RootModel[CreateObsGeometry | str]):
    root: CreateObsGeometry | str


class CreateObservationBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_id: str
    reference_code: str
    acquired_at: str
    reported_at: str | None = None
    geometry: ObsGeometryInput


class UpdateObservationBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reference_code: str | None = None
    geometry: ObsGeometryInput | None = None
    observed_at: str | None = None


class LayerStatisticsDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    count: float
    LCL_95: float
    max: float
    mean: float
    median: float | None = None
    min: float
    std: float
    UCL_95: float
    variance: float | None = None


class PreviewItem(BaseModel):
    path: str
    format: str


class LayerDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float
    field_id: str
    created_at: str
    updated_at: str
    acquired_at: str
    type_id: str
    type_name: str | None = None
    statistics: LayerStatisticsDto
    path: str
    preview: list[PreviewItem]


class PaginatedResponseLayerDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[LayerDto]
    pagination: PaginationInfo


class LayerSortBy(Enum):
    acquired_at = 'acquired_at'
    created_at = 'created_at'
    updated_at = 'updated_at'


class GetLayersQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: float | None = 1
    limit: float | None = None
    order: Order | None = 'asc'
    sort_by: Annotated[LayerSortBy | None, Field(description='Column to sort by')] = (
        None
    )
    layer_type_id: Annotated[
        str | None, Field(description='Optional project collection filter')
    ] = None
    start_date: Annotated[
        str | None, Field(description='Target CRS (coordinate reference system)')
    ] = None
    end_date: str | None = None


class SingleResponseLayerDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: LayerDto
    message: str | None = None


class ExportFormat(Enum):
    tiff = 'tiff'
    png = 'png'
    geojson = 'geojson'
    shapefile = 'shapefile'
    geopackage = 'geopackage'
    csv = 'csv'
    svg = 'svg'


class ExportDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    download_url: str
    filename: str
    format: ExportFormat
    expires_in: float
    size_bytes: float | None = None


class SingleResponseExportDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: ExportDto
    message: str | None = None


class LayerTypeDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    name: str
    group_name: str
    stacked: bool
    vector: bool
    preview_image_url: str


class PaginatedResponseLayerTypeDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[LayerTypeDto]
    pagination: PaginationInfo


class LayerTypeSortBy(Enum):
    name = 'name'
    created_at = 'created_at'
    updated_at = 'updated_at'


class GetLayerTypesQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: float | None = 1
    limit: float | None = None
    order: Order | None = 'asc'
    lang: Annotated[
        SupportedLanguage | None, Field(description='Language for field labels')
    ] = None
    sort_by: Annotated[
        LayerTypeSortBy | None, Field(description='Column to sort by')
    ] = None
    layer_sensor_id: Annotated[
        str | None, Field(description='Optional project collection filter')
    ] = None


class FieldAddress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    road: str | None = None
    town: str | None = None
    village: str | None = None
    city: str | None = None
    state: str | None = None
    street: str | None = None
    country: str | None = None
    postcode: str | None = None
    country_code: str | None = None
    house_number: str | None = None
    municipality: str | None = None
    neighbourhood: str | None = None
    ISO3166_2_lvl4: Annotated[str | None, Field(alias='ISO3166-2-lvl4')] = None


class IRecordOfAny(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class FieldDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    name: str
    address: FieldAddress
    area_ha: float
    geometry: str
    created_at: AwareDatetime
    updated_at: AwareDatetime
    deleted_at: AwareDatetime | None = None
    properties: IRecordOfAny | None = None
    country_code: str | None = None
    reference_point: str | None = None


class PaginatedResponseFieldDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[FieldDto]
    pagination: PaginationInfo


class FieldSortBy(Enum):
    name = 'name'
    created_at = 'created_at'
    updated_at = 'updated_at'


class FieldOutputFormat(Enum):
    wkt = 'wkt'
    geojson = 'geojson'


class GetFieldsQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: float | None = 1
    limit: float | None = None
    order: Order | None = 'asc'
    lang: Annotated[
        SupportedLanguage | None, Field(description='Language for field labels')
    ] = None
    sort_by: Annotated[FieldSortBy | None, Field(description='Column to sort by')] = (
        None
    )
    projectCollectionId: Annotated[
        str | None, Field(description='Optional project collection filter')
    ] = None
    crs: Annotated[
        float | None, Field(description='Target CRS (coordinate reference system)')
    ] = 4326
    output_format: Annotated[
        FieldOutputFormat | None,
        Field(description="Output format for fields: 'wkt' or 'geojson'"),
    ] = None


class Type3(Enum):
    Polygon = 'Polygon'


class CreateFieldGeometry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type3
    coordinates: list[list[list[float]]]


class CreateFieldProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None


class CreateFieldBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_id: str
    name: str
    geometry: str | CreateFieldGeometry
    properties: CreateFieldProperties | None = None


class GetFieldsLocationQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lat: Annotated[float, Field(description='Column to sort by')]
    long: Annotated[float, Field(description='Optional project collection filter')]


class GetFieldQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lang: Annotated[
        SupportedLanguage | None, Field(description='Language for field labels')
    ] = None
    crs: Annotated[
        float | None, Field(description='Target CRS (coordinate reference system)')
    ] = 4326
    output_format: Annotated[
        FieldOutputFormat | None,
        Field(description="Output format for fields: 'wkt' or 'geojson'"),
    ] = None


class FieldGeometryInput(RootModel[CreateFieldGeometry | str]):
    root: CreateFieldGeometry | str


class UpdateFieldBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = None
    geometry: FieldGeometryInput | None = None


class CropDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[int, Field(ge=0)]
    name: str
    created_at: AwareDatetime
    updated_at: AwareDatetime


class PaginatedResponseCropDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[CropDto]
    pagination: PaginationInfo


class SortBy1(Enum):
    code = 'code'
    name = 'name'
    created_at = 'created_at'
    updated_at = 'updated_at'


class GetCropsQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: float | None = 1
    limit: float | None = None
    order: Order | None = 'asc'
    lang: SupportedLanguage | None = None
    sort_by: SortBy1 | None = 'code'


class CropVarietyDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[int, Field(ge=0)]
    crop_code: Annotated[int, Field(ge=0)]
    name: str
    created_at: AwareDatetime
    updated_at: AwareDatetime


class PaginatedResponseCropVarietyDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[CropVarietyDto]
    pagination: PaginationInfo


class SortBy2(Enum):
    crop_code = 'crop_code'
    name = 'name'
    created_at = 'created_at'
    updated_at = 'updated_at'


class GetCropsVarietyQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: float | None = 1
    limit: float | None = None
    order: Order | None = 'asc'
    lang: SupportedLanguage | None = None
    sort_by: SortBy2 | None = 'crop_code'


class CultivationCropInfoDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[int, Field(ge=0)]
    name: str
    variety_id: Annotated[int, Field(ge=0)]
    variety_code: Annotated[int, Field(ge=0)]
    variety_name: str


class CultivationEventDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: str
    date: AwareDatetime


class CultivationCalendarDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[int, Field(ge=0)]
    field_id: str
    field_name: str
    season: Annotated[int, Field(ge=0)]
    crop: CultivationCropInfoDto
    events: list[CultivationEventDto]
    created_at: AwareDatetime
    updated_at: AwareDatetime


class PaginatedResponseCultivationCalendarDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[CultivationCalendarDto]
    pagination: PaginationInfo


class CultivationSortBy(Enum):
    created_at = 'created_at'
    updated_at = 'updated_at'


class GetCultivationQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: float | None = 1
    limit: float | None = None
    order: Order | None = 'asc'
    lang: Annotated[
        SupportedLanguage | None, Field(description='Language for field labels')
    ] = None
    sort_by: Annotated[
        CultivationSortBy | None, Field(description='Column to sort by')
    ] = None


class CreateFieldCultivationBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    crop_code: Annotated[int, Field(ge=0)]
    crop_variety_code: Annotated[int, Field(ge=0)]
    events: list[CultivationEventDto]


class UpdateCultivationBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    crop_code: Annotated[int | None, Field(ge=0)] = None
    crop_variety_code: Annotated[int | None, Field(ge=0)] = None
    events: list[CultivationEventDto] | None = None


class TsumPointDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: AwareDatetime
    dayDelta: float
    value: float


class CultivationCalendarTsumDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float
    field_id: str
    crop: CultivationCropInfoDto
    events: list[CultivationEventDto]
    tsum: list[TsumPointDto]


class SingleResponseCultivationCalendarTsumDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: CultivationCalendarTsumDto
    message: str | None = None
