# generated by datamodel-codegen:
#   filename:  swagger-v3.json
#   timestamp: 2026-03-30T21:47:32+00:00

from __future__ import annotations

from typing import Any

from pydantic import RootModel


class AnyModel(RootModel[dict[str, Any]]):
    root: dict[str, Any]
